name: flutter_popup_menulist
description: This can display popup menu list by using tree structure. Compatible with Android & iOS.
version: 0.0.1
author: Martin <xiaofan232@gmail.com>
homepage: https://github.com/xiaofan232/flutter_popup_menulist

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  list_treeview: ^0.2.5+1
  flutter_cache_manager: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: