name: flutter_popup_menulist
description: This can display popup menu list by using tree structure. Compatible with Android & iOS.
version: 0.0.4
homepage: https://github.com/xiaofan232/flutter_popup_menulist

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  list_treeview: ^0.3.1
  cached_network_image: 3.2.3
  file: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: